alias vi='vi -O'
alias ping='ping -c 3'
alias ping6='ping6 -c 3'
alias rm='rm -I'
alias diff='diff -sEI --suppress-common-lines'
alias cmaken='cmake -G Ninja'
alias maken='ninja -v -j 0'
alias makej='make -j$(nproc)'
alias makef='make -j$(nproc) -Wfatal-errors'
alias grepcpp='grep -rin $1 --include=*.h --include=*.hpp --include=*.cpp --include=*.c'
alias grepcmake='grep -rin $1 --include=CMakeLists.txt --include=*.cmake'
alias grepgfx='grep -rin $1 --exclude-dir=glfw --exclude-dir=build'
alias ffind='find . -name'
alias apt-depends='apt-cache rdepends --installed'
alias amend='git commit --amend'
alias disk_usage='du --summarize --human-readable'
alias cxx_opt='g++ -march=native -O2'
alias cxx_dbg='g++ -mach=native -Og'
alias copilot_do='gh copilot suggest'
alias copilot='gh copilot explain'
alias logs='git log --decorate --oneline --color -n 10 --date=local --pretty=format:"%C(yellow)%h%C(reset) %C(dim green)%ad%C(reset) %x09 %C(italic dim green)(%cr)%C(reset)%x09 %C(cyan)%d%(reset) %s %C(dim cyan)<%an>%C(reset)" .'
