alias vi='vi -O'
alias ping='ping -c 3'
alias ping6='ping6 -c 3'
alias rm='rm -I'
alias diff='diff -sEI --suppress-common-lines'
alias mm='cmake -G Ninja'
alias nn='ninja -v -j 0'
alias makej='make -j$(nproc)'
alias makef='make -j$(nproc) -Wfatal-errors'
alias grepcpp='grep -rin $1 --include=*.h --include=*.hpp --include=*.cpp --include=*.c'
alias grepcmake='grep -rin $1 --include=CMakeLists.txt --include=*.cmake'
alias grepgfx='grep -rin $1 --exclude-dir=glfw --exclude-dir=build'
alias ffind='find . -name'
alias apt-depends='apt-cache rdepends --installed'
alias amend='git commit --amend'
alias disk_usage='du --summarize --human-readable'
alias cxx_opt='g++ -march=native -O2'
alias cxx_dbg='g++ -mach=native -Og"
